version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: iris-demo
    hostname: $LOGNAME-iris-demo
    ports:
      - 1972
      - 12773:52773
      - 53773

