version: '3.6'
networks:
  irisnetworktescase:
    ipam:
      driver: default
      config:
        - subnet: 170.30.0.0/24
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: testcase-import
    hostname: testcase-import
    ports:
      - 1972
      - 12773:52773
      - 53773
    command: --check-caps false
    # environment:
    #   - ISC_DATA_DIRECTORY=/irisdata
    volumes:
      - ./data:/data
      # - ./irisdata:/irisdata
    networks:
      irisnetworktescase:
        ipv4_address: 170.30.0.10
  webgateway:
    hostname: webgateway
    container_name: webgateway
    depends_on:
      - iris
    image: containers.intersystems.com/intersystems/webgateway-arm64:latest-em
    ports:
    - 444:443
    - 81:80
    environment:
      - ISC_DATA_DIRECTORY=/webgateway
      - IRIS_USER=CSPsystem
      - IRIS_PASSWORD=SYS
    networks:
      irisnetworktescase:
        ipv4_address: 170.30.0.200
    volumes:
      - "./volumes/webgateway:/webgateway"

